#!/bin/bash

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "stow $folder"
    stow -D $folder
    stow $folder
done
popd

# pushd ./private
# ./stow
# popd
#
# pushd ./tricent
# ./stow
# popd

