#!/bin/bash

if [[ -z $STOW_FOLDERS ]]; then
  STOW_FOLDERS="nvim,starship,tmux,vimrc,wezterm,zsh"
fi

if [[ -z $DOTFILES ]]; then
  DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
