#!/bin/bash

# Define an array of font files
FONT_FILES=(
  "fonts/JetBrainsMonoNerdFont-ExtraBold.ttf"
  "fonts/JetBrainsMonoNerdFont-ExtraBoldItalic.ttf"
  "fonts/JetBrainsMonoNerdFont-ExtraLight.ttf"
  "fonts/JetBrainsMonoNerdFont-ExtraLightItalic.ttf"
  "fonts/JetBrainsMonoNerdFont-Italic.ttf"
  "fonts/JetBrainsMonoNerdFont-Light.ttf"
  "fonts/JetBrainsMonoNerdFont-LightItalic.ttf"
  "fonts/JetBrainsMonoNerdFont-Medium.ttf"
  "fonts/JetBrainsMonoNerdFont-MediumItalic.ttf"
  "fonts/JetBrainsMonoNerdFont-Regular.ttf"
  "fonts/JetBrainsMonoNerdFont-SemiBold.ttf"
  "fonts/JetBrainsMonoNerdFont-SemiBoldItalic.ttf"
  "fonts/JetBrainsMonoNerdFont-Thin.ttf"
  "fonts/JetBrainsMonoNerdFont-ThinItalic.ttf"
)

# Set the destination directory for fonts on macOS
FONT_DESTINATION="/Library/Fonts"

# Iterate through the array of font files
for FONT_FILE in "${FONT_FILES[@]}"; do
  # Check if the font file exists
  if [ ! -f "$FONT_FILE" ]; then
    echo "Font file not found: $FONT_FILE"
  else
    # Copy the font file to the destination directory
    cp "$FONT_FILE" "$FONT_DESTINATION"
    echo "Font installed successfully: $(basename "$FONT_FILE")"
  fi
done

# Install stow
brew install stow
echo "Stow installed successfully."

# Install Neovim
brew install neovim
echo "Neovim installed successfully."

# Install Node (Neovim LSP dependency)
brew install node
echo "Node installed succesfully"

# Install Node Version Manager
brew install nvm
echo "NVM installed successfully"
mkdir ~/.nvm

# Install Python version manager
brew install pyenv pyenv-virtualenv
echo "Pyenv installed successfully"

# Install tmux
brew install tmux
echo "TMUX installed successfully"

# Install ripgrep (NVIM telescope dependency)
brew install ripgrep
echo "Ripgrep installed successfully"

# Install lazygit
brew install lazygit
echo "Lazygit installed successfully"

# Install WezTerm
brew install --cask wezterm
echo "Wezterm installed successfully"

# Install Starship
brew install starship
echo "Starship installed successfully"

# Install zsh-highlight & zsh-autosuggestions
brew install zsh-syntax-highlighting zsh-autosuggestions
echo "Syntax Highlighting & Autosuggestions installed successfully"
